## If want you execute by other on environment.
# ansible-playbook site.yml -e exec_group_hosts=production
- name: adapted in prometheus node-exporter.
  hosts: "{{ exec_group_hosts | default('node') }}"
  become: yes
  ## Case to expired end of the cache.
  # ansible-playbook site.yml -e exec_gather_facts=true
  ## Case to add of any nodes.
  # ansible-playbook -l NEWNODEALIAS site.yml -e exec_gather_facts=true
  gather_facts: "{{ exec_gather_facts | default(true) }}"
  roles:
    - prometheus_node
