---
node_exporter_version: '0.14.0'
node_exporter_name: "node_exporter-{{ node_exporter_version }}.linux-amd64"
node_exporter_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"