---
- name: PHP Install | include vars
  include_vars: php.yml


- name: PHP Install | php_upgrade
  yum:
    name: "php*"
    state: latest
    enablerepo: remi-php56


- name: PHP Install | php_additional_install
  yum:
    name: "{{ item }}"
    state: present
    enablerepo: remi-php56
  with_items: "{{ php_56_cli_mods_dependencies }}"