---
- name: Firewalld Configure | check if firewalld is running
  shell: systemctl is-active firewalld
  register: firewalld_result
  changed_when: False
  ignore_errors: True


- name: Firewalld Configure | insert firewalld rule for sshd
  firewalld:
    port: "{{item.port}}/{{item.protocol}}" 
    permanent: "{{item.permanent}}" 
    state: "{{item.state }}"
    zone: "{{item.zone}}"
    immediate: yes
  with_items:
    - { port: '22', protocol: 'tcp', permanent: true, state: 'enabled', zone: 'public' }
  notify: restart_firewalld