remote_user: vagrant
ssh_port: 22
mainte_user: testuser
mainte_group: testgroup


locale:
  language:
    jp: "ja_JP.utf8"
  timezone:
    jst: Asia/Tokyo
    utc: Atlantic/St_Helena


internal_network: "192.168.35.0/24"


# =======================================================================
# ユーザ情報の変数定義
# Ansibleではパスワードをハッシュ化する必要があるため、pythonのコマンドにてハッシュ化したパスワードを設定
# python -c 'import crypt; print crypt.crypt("パスワード", "$6$ソルト$")'
# =======================================================================
usergroup:
  user01:
    user: "{{ mainte_user }}"
    group: "{{ mainte_group }}"
    uid: 1001
    gid: 1001
    home: /home/"{{ mainte_user }}"
    shell: /bin/bash
    # =======================================================================
    # python -c 'import crypt; print crypt.crypt("Gv2N863c", "$6$UserSolt$")'
    # =======================================================================
    password: $6$"{{ mainte_user }}"Solt$dmoMxd2sKA5VMsgH7M/GH8RKW9BwqIca4nN6CC72oEeKlqaG2/tgp.6yK1NqATdtm7PZmifEX5rLyhA4pLXmK/
