# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    environment: production
    service: Prometheus
    monitor: Other

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 15 seconds.
    scrape_interval: 15s
    scrape_timeout: 10s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090', 'localhost:9100']

  - job_name: 'ec2_node_other'
    # Override the global default and scrape targets from this job every 15 seconds.
    scrape_interval: 15s
    scrape_timeout: 10s

    # EC2 Service Discovery Config
    ec2_sd_configs:
      - region: 'ap-northeast-1'
        access_key: 'acc_key'
        secret_key: 'sec_key'
        port: 9100

    relabel_configs:
      - source_labels: [__meta_ec2_tag_Project]
        regex: Other
        action: keep

      #- source_labels: [__meta_ec2_tag_Role]
      #  regex: monitor
      #  action: drop

  - job_name: 'ec2_snmp_other'
    # Override the global default and scrape targets from this job every 15 seconds.
    scrape_interval: 15s
    scrape_timeout: 10s

    # EC2 Service Discovery Config
    ec2_sd_configs:
      - region: 'ap-northeast-1'
        access_key: 'acc_key'
        secret_key: 'sec_key'
        port: 9116
    metrics_path: /snmp
    params:
      module: [default]
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Project]
        regex: Other
        action: keep
    relabel_configs:
      - target_label: __param_target
        replacement: 127.0.0.1

#  - job_name: 'snmp'
#    static_configs:
#      - targets: ['localhost']
#    params:
#      module: [default]
#    relabel_configs:
#      - source_labels: [__address__]
#        regex: (.*?)(:80)?
#        target_label: __param_address
#        replacement: ${1}
#      - source_labels: [__param_address]
#        regex: (.*)
#        target_label: instance
#        replacement: ${1}
#      - source_labels: []
#        regex: .*
#        target_label: __address__
#        replacement: localhost:9116